server:
  port: 9097

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uber2025_rideservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: ride-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: env